jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Obs\SecurityBundle\Entity\Users: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_MODERATOR]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ADMIN]

    providers:
        entity:
          entity: {class: Obs\SecurityBundle\Entity\Users, property: username }

    firewalls:              
        login_filrewall:
            pattern: ^/login$
            anonymous: ~
      
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check

            logout:
                path: logout
                target: /
                #resolve warning bug
                invalidate_session: false
              
    access_control:
        - { path: ^/admin,  role: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https}


#apagar depois
#    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
# 
#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
#
#    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
#apagar depois
#    firewalls:
    #    dev:
    #        pattern:  ^/(_(profiler|wdt)|css|images|js)/
    #        security: false

    #    login:
    #        pattern:  ^/demo/secured/login$
    #        security: false

    #   secured_area:
        #    pattern:    ^/demo/secured/
        #   form_login:
            #    check_path: _security_check
            #    login_path: _demo_login
            #logout:
            #    path:   _demo_logout
            #    target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
 
