<?php

namespace Obs\CoreBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PublicationController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Obs\CoreBundle\Controller\PublicationController();
        return $instance;
    }
}
